test backup

diff --git a/k8s/vaultwarden/export-and-backup/overlays/ionos.com/cronjob-patch.yaml b/k8s/vaultwarden/export-and-backup/overlays/ionos.com/cronjob-patch.yaml
--- a/k8s/vaultwarden/export-and-backup/overlays/ionos.com/cronjob-patch.yaml
+++ b/k8s/vaultwarden/export-and-backup/overlays/ionos.com/cronjob-patch.yaml
@@ -9,9 +9,6 @@ spec:
     spec:
       template:
         spec:
-
-
-
           containers:
             - name: ionos-com-objectstorage-eu-central-3-s3-kopia-backup
               image: ghcr.io/tryrocket-cloud/tryrocket-cloud:backup
@@ -80,54 +77,54 @@ spec:
                   mountPath: /export
                   readOnly: true
 
-            - name: ionos-com-objectstorage-eu-central-3-s3-restic-backup
-              image: ghcr.io/tryrocket-cloud/tryrocket-cloud:backup
-              imagePullPolicy: Always
-              env:
-                - name: VAULTWARDEN_EXPORT_JSON
-                  value: /export/vaultwarden-export.json
-                - name: RESTIC_CACHE_DIR
-                  value: /cache/ionos.com/vaultwarden/restic
-                - name: HOSTNAME
-                  value: tryrocket.cloud
-              envFrom:
-                - secretRef:
-                    name: ionos-com-s3-bucket-configuration
-                - secretRef:
-                    name: ionos-com-s3-credentials
-                - secretRef:
-                    name: ionos-com-restic-repository-configuration
-                - secretRef:
-                    name: ionos-com-healthchecks-configuration
-              command:
-                  - /bin/sh
-                  - -c
-                  - |
-                    cat /etc/environment
+            # - name: ionos-com-objectstorage-eu-central-3-s3-restic-backup
+            #   image: ghcr.io/tryrocket-cloud/tryrocket-cloud:backup
+            #   imagePullPolicy: Always
+            #   env:
+            #     - name: VAULTWARDEN_EXPORT_JSON
+            #       value: /export/vaultwarden-export.json
+            #     - name: RESTIC_CACHE_DIR
+            #       value: /cache/ionos.com/vaultwarden/restic
+            #     - name: HOSTNAME
+            #       value: tryrocket.cloud
+            #   envFrom:
+            #     - secretRef:
+            #         name: ionos-com-s3-bucket-configuration
+            #     - secretRef:
+            #         name: ionos-com-s3-credentials
+            #     - secretRef:
+            #         name: ionos-com-restic-repository-configuration
+            #     - secretRef:
+            #         name: ionos-com-healthchecks-configuration
+            #   command:
+            #       - /bin/sh
+            #       - -c
+            #       - |
+            #         cat /etc/environment
 
-                    export VAULTWARDEN_VERSION=$(cat /export/vaultwarden.env)
-                    export RESTIC_VERSION=$(restic version | awk '{print $2}')
-                    export RESTIC_REPOSITORY="s3:$ENDPOINT/$BUCKET/$PREFIX"
+            #         export VAULTWARDEN_VERSION=$(cat /export/vaultwarden.env)
+            #         export RESTIC_VERSION=$(restic version | awk '{print $2}')
+            #         export RESTIC_REPOSITORY="s3:$ENDPOINT/$BUCKET/$PREFIX"
 
-                    [ -z "$VAULTWARDEN_VERSION" ] && exit 1
-                    [ -z "$RESTIC_VERSION" ] && exit 1
-                    [ -z "$RESTIC_REPOSITORY" ] && exit 1
+            #         [ -z "$VAULTWARDEN_VERSION" ] && exit 1
+            #         [ -z "$RESTIC_VERSION" ] && exit 1
+            #         [ -z "$RESTIC_REPOSITORY" ] && exit 1
 
-                    # Start health check
-                    #curl -fsS -m 10 --retry 5 $HC_PING_URL/start
+            #         # Start health check
+            #         #curl -fsS -m 10 --retry 5 $HC_PING_URL/start
 
-                    # Perform restic backup
-                    restic backup --host "$HOSTNAME" --tag restic:"$RESTIC_VERSION" --tag vaultwarden:"$VAULTWARDEN_VERSION" --tag export $VAULTWARDEN_EXPORT_JSON
-                    #curl -fsS -m 10 --retry 5 $HC_PING_URL/$?
+            #         # Perform restic backup
+            #         restic backup --host "$HOSTNAME" --tag restic:"$RESTIC_VERSION" --tag vaultwarden:"$VAULTWARDEN_VERSION" --tag export $VAULTWARDEN_EXPORT_JSON
+            #         #curl -fsS -m 10 --retry 5 $HC_PING_URL/$?
 
-                    # Perform restic check
-                    restic check --read-data-subset 1/3
-                    #curl -fsS -m 10 --retry 5 $HC_PING_URL/$?
+            #         # Perform restic check
+            #         restic check --read-data-subset 1/3
+            #         #curl -fsS -m 10 --retry 5 $HC_PING_URL/$?
 
-                    # Prune old backups
-                    restic forget --keep-daily 30 --keep-monthly 3 --keep-yearly 1 --prune
-                    curl -fsS -m 10 --retry 5 https://hc-ping.com/$RESTIC_HC_UUID
-              volumeMounts:
-                - name: vaultwarden-export-volume
-                  mountPath: /export
-                  readOnly: true
+            #         # Prune old backups
+            #         restic forget --keep-daily 30 --keep-monthly 3 --keep-yearly 1 --prune
+            #         curl -fsS -m 10 --retry 5 https://hc-ping.com/$RESTIC_HC_UUID
+            #   volumeMounts:
+            #     - name: vaultwarden-export-volume
+            #       mountPath: /export
+            #       readOnly: true
